version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - '5438:5432'
   # volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
#      # copy the sql script to create tables
#      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#      # copy the sql script to fill tables
#      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
    - "5671:5671"
    - "5672:5672"
  bankservices:
    image: adroitdev/bankservice
    restart: always
    ports:
    - 8080:9090
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://localhost:5432/bankservicedb'
      SPRING_RABBITMQ_HOST: rabbitmq
